/**
 * Heroes of Empires - species
 * OE Microservice Project
 *
 * OpenAPI spec version: v1
 * Contact: krisztian@mozilla.hu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { Species } from '../model/species';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class SpeciesResourceService {

    protected basePath = 'http://localhost:8090/species';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * Faj tulajdonságainak módosítása.
     * @param sid 
     * @param aid 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public addAbilityToSpecies(sid: number, aid: number, observe?: 'body', reportProgress?: boolean): Observable<Species>;
    public addAbilityToSpecies(sid: number, aid: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Species>>;
    public addAbilityToSpecies(sid: number, aid: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Species>>;
    public addAbilityToSpecies(sid: number, aid: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (sid === null || sid === undefined) {
            throw new Error('Required parameter sid was null or undefined when calling addAbilityToSpecies.');
        }

        if (aid === null || aid === undefined) {
            throw new Error('Required parameter aid was null or undefined when calling addAbilityToSpecies.');
        }

        let headers = this.defaultHeaders;

        // authentication (jwt-token) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Species>('get',`${this.basePath}/species/removeability/${encodeURIComponent(String(sid))}/${encodeURIComponent(String(aid))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Új faj felvitele.
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public addSpecies(body?: Species, observe?: 'body', reportProgress?: boolean): Observable<Array<Species>>;
    public addSpecies(body?: Species, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Species>>>;
    public addSpecies(body?: Species, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Species>>>;
    public addSpecies(body?: Species, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // authentication (jwt-token) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*',
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<Array<Species>>('post',`${this.basePath}/species`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Elérhető fajok lekérdezése.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllSpecies(observe?: 'body', reportProgress?: boolean): Observable<Array<Species>>;
    public getAllSpecies(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Species>>>;
    public getAllSpecies(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Species>>>;
    public getAllSpecies(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // authentication (jwt-token) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<Species>>('get',`${this.basePath}/species/getallspecies`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Egy elérhető faj keresése név azonosító.
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getSpeciesById(id: number, observe?: 'body', reportProgress?: boolean): Observable<Species>;
    public getSpeciesById(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Species>>;
    public getSpeciesById(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Species>>;
    public getSpeciesById(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getSpeciesById.');
        }

        let headers = this.defaultHeaders;

        // authentication (jwt-token) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Species>('get',`${this.basePath}/species/byid/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Egy elérhető faj keresése név alapján.
     * @param name 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getSpeciesByName(name: string, observe?: 'body', reportProgress?: boolean): Observable<Species>;
    public getSpeciesByName(name: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Species>>;
    public getSpeciesByName(name: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Species>>;
    public getSpeciesByName(name: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (name === null || name === undefined) {
            throw new Error('Required parameter name was null or undefined when calling getSpeciesByName.');
        }

        let headers = this.defaultHeaders;

        // authentication (jwt-token) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Species>('get',`${this.basePath}/species/byname/${encodeURIComponent(String(name))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Faj tulajdonságainak módosítása.
     * @param sid 
     * @param aid 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public removeAbilityFromSpecies(sid: number, aid: number, observe?: 'body', reportProgress?: boolean): Observable<Species>;
    public removeAbilityFromSpecies(sid: number, aid: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Species>>;
    public removeAbilityFromSpecies(sid: number, aid: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Species>>;
    public removeAbilityFromSpecies(sid: number, aid: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (sid === null || sid === undefined) {
            throw new Error('Required parameter sid was null or undefined when calling removeAbilityFromSpecies.');
        }

        if (aid === null || aid === undefined) {
            throw new Error('Required parameter aid was null or undefined when calling removeAbilityFromSpecies.');
        }

        let headers = this.defaultHeaders;

        // authentication (jwt-token) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Species>('get',`${this.basePath}/species/romoveability/${encodeURIComponent(String(sid))}/${encodeURIComponent(String(aid))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
