version: '3.4'
services:

  portaldb:
    image: mariadb:10.1.34
    environment:
      MYSQL_ROOT_PASSWORD: QVX6JV1HjaNN4cBLjVmqfF2dQmzbzqFEipMLt6sR
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: SuMFWGU410c4Fbwri0CWGJsGnUJwo7QAVtJDFwDHc
    ports:
      - '13306:3306'
    restart: on-failure
    volumes:
     - /home/user/jdebug/mysql/:/var/lib/mysql
     - /home/user/jdebug/mysqlconfig:/etc/mysql/conf.d

  keycloak:
    # image: jboss/keycloak:4.1.0.Final
    image: jboss/keycloak:6.0.1
    environment:
      MYSQL_ADDR: portaldb
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: SuMFWGU410c4Fbwri0CWGJsGnUJwo7QAVtJDFwDHc
      KEYCLOAK_USER: admin4d
      KEYCLOAK_PASSWORD: sIfnzEUQAK4TCDGeftwyDKsUg58ryTMt7Yd5C56a
#      PROXY_ADDRESS_FORWARDING: "true"
#      KEYCLOAK_HOSTNAME: portal.tavdoktor.hu
    depends_on:
      - portaldb
    ports:
      - '9080:8080'
#      - '9443:8443'
    restart: on-failure
#    volumes:
#     - ${PWD}/cert:/etc/x509/https



  hoe-species:
    image: jkqxl2/hoe:species
    volumes:
      - /home/user/jdebug:/opt/jdebug
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://10.0.2.15:3306/hoe
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: user
      JAVA_OPTS: -javaagent:/opt/jdebug/jidebugplus-agent-1.0-SNAPSHOT.jar=config:/opt/jdebug/agent-species.properties
      KEYCLOAK_AUTH_SERVER_URL: http://hoeservice:9080/auth
    extra_hosts:
      hoeservice: 10.0.2.15
    ports:
      - '8090:8090'

  hoe-heroes:
    image: jkqxl2/hoe:heroes
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://10.0.2.15:3306/hoe
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: user
      SERVICE_SPACES: http://hoe-species:8090/species
      KEYCLOAK_AUTH_SERVER_URL: http://hoeservice:9080/auth
      JAVA_OPTS: -javaagent:/opt/jdebug/jidebugplus-agent-1.0-SNAPSHOT.jar=config:/opt/jdebug/agent-heroes.properties
    volumes:
      - /home/user/jdebug:/opt/jdebug
    extra_hosts:
      hoeservice: 10.0.2.15
    ports:
      - '8091:8091'

  hoe-empire:
    image: jkqxl2/hoe:empire
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://10.0.2.15:3306/hoe
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: user
      SERVICE_HERO: http://hoe-heroes:8091/heroes
      KEYCLOAK_AUTH_SERVER_URL: http://hoeservice:9080/auth
      JAVA_OPTS: -javaagent:/opt/jdebug/jidebugplus-agent-1.0-SNAPSHOT.jar=config:/opt/jdebug/agent-empire.properties
    volumes:
      - /home/user/jdebug:/opt/jdebug
    extra_hosts:
      hoeservice: 10.0.2.15
    ports:
      - '8092:8092'



  hoe-angular:
    image: jkqxl2/hoe:angular
    extra_hosts:
      hoeservice: 10.0.2.15
    ports:
      - '4200:80'



