/**
 * Heroes of Empires - empire
 * OE Microservice Project
 *
 * OpenAPI spec version: v1
 * Contact: krisztian@mozilla.hu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SecurityGuard } from './securityGuard';

export interface Empire { 
    id?: number;
    name?: string;
    description?: string;
    protect?: SecurityGuard;
}