/**
 * Heroes of Empires - empire
 * OE Microservice Project
 *
 * OpenAPI spec version: v1
 * Contact: krisztian@mozilla.hu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface SecurityGuard { 
    id?: number;
    starttime?: Date;
    stoptime?: Date;
    active?: boolean;
    price?: number;
    heroid?: number;
    empireid?: number;
}