/**
 * Heroes of Empires - Hero
 * OE Microservice Project
 *
 * OpenAPI spec version: v1
 * Contact: krisztian@mozilla.hu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Species } from './species';

export interface Hybrid { 
    id?: number;
    percent?: string;
    speciesid?: number;
    species?: Species;
}