/**
 * Heroes of Empires - Hero
 * OE Microservice Project
 *
 * OpenAPI spec version: v1
 * Contact: krisztian@mozilla.hu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Ability } from './ability';

export interface Species { 
    id?: number;
    name?: string;
    description?: string;
    endowments?: Array<Ability>;
}