/**
 * Heroes of Empires
 * OE Microservice Project
 *
 * OpenAPI spec version: v1
 * Contact: krisztian@mozilla.hu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Ability { 
    id?: number;
    name: string;
    description: string;
    skill?: string;
    brain?: string;
    power?: string;
}